# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_add_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='allowed_radius_meters',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='attendances', to='attendance.course'),
        ),
    ]
