# Generated by Django 5.0.7 on 2026-01-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_emailverificationtoken_passwordresettoken'),
        ('attendance', '0015_organization_course_organization_and_more'),
    ]

    operations = [
    ]
